import { StyleSheet } from 'react-native';
import { FontFamily, FontSize, Color, Padding, Border } from ".../../../GlobalStyles";

const styles = StyleSheet.create({
    headershadowPosition: {
      top: 0,
      position: "absolute",
    },
    signup2Typo: {
      fontFamily: FontFamily.poppinsBold,
      fontWeight: "700",
    },
    overallLayout: {
      width: 360,
      position: "absolute",
    },
    footerFlexBox: {
      justifyContent: "center",
      flexDirection: "row",
      position: "absolute",
    },
    continuePosition: {
      top: "0%",
      left: "0%",
      position: "absolute",
    },
    googleTypo1: {
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    signUpTypo: {
      fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
    },
    buttonsPosition: {
      bottom: "34.02%",
      top: "28.87%",
      height: "37.11%",
      position: "absolute",
    },
    googleTypo: {
      fontSize: FontSize.size_xs,
      color: Color.colorWhite,
      textAlign: "left",
    },
    emailPosition: {
      width: 289,
      left: 39,
      position: "absolute",
    },
    iconLayout: {
      height: 55,
      width: 289,
      left: 0,
      position: "absolute",
    },
    inputemailLayout: {
      height: 53,
      width: 239,
      position: "absolute",
      overflow: "hidden",
    },
    passwordiconPosition: {
      left: "7.96%",
      width: "5.19%",
      right: "86.85%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    icon: {
      backgroundColor: "transparent",
      height: "100%",
      width: "100%",
    },
    backgroundImage: {
      right: -5,
      width: 717,
      height: 490,
    },
    headershadow: {
      left: -49,
      width: 601,
      height: 134,
      backgroundColor: "transparent",
    },
    logoIcon: {
      width: 91,
      height: 31,
    },
    haveAnAccount: {
      color: Color.colorSilver,
    },
    login: {
      color: Color.colorWhite,
    },
    dosignuptext: {
      letterSpacing: 0.8,
      width: 216,
      marginLeft: 86,
      textAlign: "left",
      fontSize: FontSize.size_3xs,
    },
    header: {
      width: 361,
      height: 93,
      paddingLeft: Padding.p_base,
      paddingTop: Padding.p_xs,
      paddingRight: Padding.p_6xs,
      alignItems: "center",
      flexDirection: "row",
      left: 0,
      top: 0,
      position: "absolute",
    },
    orContinueWith: {
      left: "0%",
      top: "0%",
      position: "absolute",
      color: Color.colorSilver,
      textAlign: "left",
      fontSize: FontSize.size_3xs,
    },
    continueWith: {
      width: "25.89%",
      right: "77.11%",
      bottom: "84.54%",
      left: "0%",
      height: "15.46%",
      top: "0%",
    },
    termsAndConditions: {
      color: Color.colorMediumslateblue,
    },
    byRegisteringYouContainer: {
      left: "0%",
      top: "0%",
      width: "100%",
      position: "absolute",
      textAlign: "left",
      fontSize: FontSize.size_3xs,
    },
    terms: {
      width: "80.57%",
      top: "84.54%",
      right: "32.43%",
      bottom: "0%",
      left: "0%",
      height: "15.46%",
      position: "absolute",
    },
    cardIcon: {
      maxHeight: "100%",
      maxWidth: "100%",
      right: "0%",
      bottom: "0%",
      left: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
      overflow: "hidden",
      width: "100%",
    },
    frameChild: {
      width: 18,
      height: 18,
    },
    facebook: {
      width: 80,
      height: 15,
      marginLeft: 8,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    groupParent: {
      right: "0%",
      bottom: "0%",
      left: "0%",
      top: "0%",
      justifyContent: "center",
      flexDirection: "row",
      height: "100%",
      position: "absolute",
      width: "100%",
    },
    buttonsInner: {
      height: "50%",
      width: "63.24%",
      top: "25%",
      right: "18.38%",
      bottom: "25%",
      left: "18.38%",
      position: "absolute",
    },
    buttons: {
      width: "37.06%",
      right: "19.89%",
      left: "43.05%",
    },
    frameItem: {
      width: 15,
      height: 16,
    },
    google: {
      marginLeft: 10,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    groupContainer: {
      height: "44.17%",
      width: "45.97%",
      top: "27.78%",
      right: "26.81%",
      bottom: "28.06%",
      left: "27.22%",
      alignItems: "center",
    },
    buttons1: {
      width: "39.24%",
      right: "60.76%",
      left: "0%",
    },
    continuewithgoogleandfb: {
      width: 367,
      height: 97,
    },
    footer: {
      top: 586,
      left: 3,
      width: 357,
      height: 124,
      flexWrap: "wrap",
      paddingLeft: Padding.p_58xl,
      paddingRight: Padding.p_9xs,
    },
    signUp: {
      fontSize: FontSize.size_mid_9,
      textAlign: "center",
      color: Color.colorWhite,
    },
    signupbutton: {
      marginTop: 152,
      right: 33,
      borderRadius: Border.br_mini,
      width: 293,
      paddingHorizontal: 0,
      paddingVertical: 11,
      top: "50%",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      backgroundColor: "transparent",
      position: "absolute",
    },
    signup2: {
      top: 10,
      left: 34,
      fontSize: FontSize.size_43xl,
      width: 297,
      color: Color.colorWhite,
      textAlign: "left",
      position: "absolute",
    },
    signup1: {
      shadowColor: "rgba(0, 0, 0, 0.25)",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowRadius: 4,
      elevation: 4,
      shadowOpacity: 1,
      height: 113,
      left: 0,
      top: 0,
    },
    usernameinputIcon: {
      top: 21,
    },
    enterusernametext: {
      textShadowColor: "rgba(0, 0, 0, 0.25)",
      textShadowOffset: {
        width: 0,
        height: 4,
      },
      textShadowRadius: 4,
      fontFamily: FontFamily.poppinsBold,
      fontWeight: "700",
      left: 0,
      top: 0,
      position: "absolute",
    },
    usernameicon: {
      height: "28.03%",
      width: "6.92%",
      bottom: "21.97%",
      left: "6.23%",
      right: "86.85%",
      top: "50%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    inputusername: {
      left: 50,
      top: 23,
    },
    username: {
      top: 123,
      height: 76,
    },
    emailinputIcon: {
      top: 25,
    },
    emailtext: {
      fontFamily: FontFamily.poppinsBold,
      fontWeight: "700",
      left: 0,
      top: 0,
      position: "absolute",
    },
    inputemail: {
      top: 26,
      left: 49,
    },
    email: {
      top: 214,
      height: 80,
    },
    passwordinputIcon: {
      top: 23,
    },
    passwordicon: {
      height: "24.36%",
      top: "51.28%",
      bottom: "24.36%",
    },
    password: {
      top: 309,
      height: 78,
    },
    confirmpasswordinputIcon: {
      top: 24,
    },
    passwordicon1: {
      height: "24.05%",
      top: "51.9%",
      bottom: "24.05%",
    },
    confirmpassword: {
      top: 402,
      height: 79,
    },
    overall: {
      top: 70,
      left: 5,
      height: 710,
    },
    signup: {
      backgroundColor: Color.colorMidnightblue,
      flex: 1,
      height: 800,
      overflow: "hidden",
      width: "100%",
    },
  });

  export default styles;